### ISSUE TITLE
Consumers are not created

### ISSUE THREAD

**Issue by cmmartin** [Phobetor/rabbitmq-supervisor-bundle#53]
I have a configuration that defines multiple consumers, but they are never created...

```yaml
    consumers:
        general:
            connection:       default
            exchange_options: {name: 'general', type: direct}
            queue_options:    {name: 'general'}
            ...
```

After running `console rabbitmq-supervisor:rebuild`

The consumers seem to be missing. I am not consuming any messages and when I run 

```sh
rabbitmqctl list_consumers
```

There are none listed. The exchanges and queues are present and everything else seems to be working fine. Any idea what is going on? I can't seem to find any errors either
