### ISSUE TITLE
"-w" flag support request

### ISSUE THREAD

**Issue by SergeC** [Phobetor/rabbitmq-supervisor-bundle#7]
From https://github.com/videlalvaro/RabbitMqBundle/blob/master/README.md#consumers 
`If you want to be sure that consumer will finish executing instantly on Unix signal, you can run command with flag -w.`
I'd like the way this bundle generates supervisor configs for consumers. Without `-w` flag it takes too long to stop consumer process which is not good for development process. Can you add optional(via config.yml) `-w` flag that will be appended to all commands if custom command not set in rabbit_mq_supervisor.commands?

**Comment by Phobetor** [comment]
Hi @SergeC 

This is available in [version 2.0.0](https://github.com/Phobetor/rabbitmq-supervisor-bundle/releases/tag/2.0.0).

You can activate the `without-signals` option by setting:
```yml
rabbit_mq_supervisor:
    consumer:
        general:
            without-signals:            true    # consumer command option: disable catching of system signals
```
