### ISSUE TITLE
Count of specific workers

### ISSUE THREAD

**Issue by Domovenok** [Phobetor/rabbitmq-supervisor-bundle#8]
How can i determine count of specific worker? Currently i can set global amount of workers

**Comment by Phobetor** [comment]
I am very sorry to tell you that there is no option to do that at the moment. This feature is priority 1 on my to-do list.

**Comment by Phobetor** [comment]
Hi @Domovenok  

This is available in [version 2.0.0](https://github.com/Phobetor/rabbitmq-supervisor-bundle/releases/tag/2.0.0).

You can set the worker count on a per consumer level by setting:
```yml
rabbit_mq_supervisor:
    consumer:
        individual:
          {{consumer name}}:
            worker:
                count:                  1       # number of workers per consumer
```
